objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On</fullName>
                </value>
                <value>
                    <fullName>Off</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On</fullName>
                </value>
                <value>
                    <fullName>Off</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContactTriggerHelper.cls
public with sharing class ContactTriggerHelper {

    public static void populateAccountOnContact(List<Contact> conList) {

        Set<Id> setOfIds = new Set<Id>();
        for(Contact con : conList) {
            setOfIds.add(con.AccountId);
        }
        List<Account> accList = [Select Id, Name, Status__c, Property__c From Account Where Id In: setOfIds];
        System.debug('accList ==> ' + accList);
        
        
        
        // Map of Account
        Map<Id, Account> mapOfAcc = new Map<Id, Account>();
        mapOfAcc.putAll(accList);
        System.debug('mapOfAcc ==> ' + mapOfAcc);
        for(Contact con : conList) {
            If(con.Status__c == null) {
                Account acc = mapOfAcc.get(con.AccountId);
                If(acc.Status__c != null) {
                    con.Status__c = acc.Status__c;
                } 
            }
        }
    }
}