objects/State__c.object
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Phone_Number__c</fullName>
        <label>Bank Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>B.A</fullName>
                    <default>true</default>
                    <label>B.A</label>
                </value>
                <value>
                    <fullName>B.SC</fullName>
                </value>
                <value>
                    <fullName>B.TECH</fullName>
                </value>
                <value>
                    <fullName>BBA</fullName>
                </value>
                <value>
                    <fullName>BCA</fullName>
                </value>
                <value>
                    <fullName>M.B.A</fullName>
                </value>
                <value>
                    <fullName>M.C.A</fullName>
                </value>
                <value>
                    <fullName>M.SC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Year__c</fullName>
        <label>Current Year</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1st Year</fullName>
                    <default>true</default>
                    <label>1st Year</label>
                </value>
                <value>
                    <fullName>2nd Year</fullName>
                </value>
                <value>
                    <fullName>3rd Year</fullName>
                </value>
                <value>
                    <fullName>4th Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Of_Birth__c</fullName>
        <label>Date Of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Donation_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Donation Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Exam_Fees_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exam Fees Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Father_Mobile_Number__c</fullName>
        <label>Father Mobile Number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Father_s_Name__c</fullName>
        <label>Father&apos;s Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fees_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fees Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <label>Home Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>IFSC_Code__c</fullName>
        <label>IFSC Code</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Donation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Donation?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mobile_number__c</fullName>
        <label>Mobile number</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Overall_Grade__c</fullName>
        <label>Overall Grade</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                    <default>true</default>
                    <label>A</label>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pending_Exam_Fees__c</fullName>
        <label>Pending Exam Fees</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pending_Fees_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Pending Fees Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pincode__c</fullName>
        <label>Pincode</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Roll_Number__c</fullName>
        <label>Roll Number</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                    <default>true</default>
                    <label>A</label>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stream__c</fullName>
        <label>Stream</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Art</fullName>
                    <default>true</default>
                    <label>Art</label>
                </value>
                <value>
                    <fullName>Commerce</fullName>
                </value>
                <value>
                    <fullName>Science</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_ID__c</fullName>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Subjects_In_which_Back_1st_sem__c</fullName>
        <label>Subjects In which Back(1st sem)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subjects_In_which_Back_2nd_sem__c</fullName>
        <label>Subjects In which Back(2nd sem)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subjects_In_which_Back_3rd_sem__c</fullName>
        <label>Subjects In which Back(3rd sem)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subjects_In_which_Back_4th_sem__c</fullName>
        <label>Subjects In which Back(4th sem)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>X1st_Sem_Back__c</fullName>
        <defaultValue>false</defaultValue>
        <label>1st Sem Back</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X1st_Sem_Percentage__c</fullName>
        <label>1st Sem Percentage</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X2nd_Sem_Back__c</fullName>
        <defaultValue>false</defaultValue>
        <label>2nd Sem Back</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X2nd_Sem_Percentage__c</fullName>
        <label>2nd Sem Percentage</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X3rd_Sem_Back__c</fullName>
        <defaultValue>false</defaultValue>
        <label>3rd Sem Back</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X3rd_Sem_Percentage__c</fullName>
        <label>3rd Sem Percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X4th_Sem_Back__c</fullName>
        <defaultValue>false</defaultValue>
        <label>4th Sem Back</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>X4th_Sem_Percentage__c</fullName>
        <label>4th Sem Percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <recordTypes>
        <fullName>Teacher</fullName>
        <active>true</active>
        <label>Teacher</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/StudentInformation.cls
public class StudentInformation {
    public static void InsertStudent() {
        Student__c student = new Student__c();
        //Personal Detail
        student.Roll_Number__c = '18455';
        student.Name = 'Govind Kumar';
        student.Father_s_Name__c = 'Suresh chandra';
        student.Father_Mobile_Number__c = '9587634783';
        student.Mobile_Number__c = '9758675436';
        student.Date_Of_Birth__c = date.parse('7/6/2002');
        student.Email__c = 'govind.kumar@gmail.com';
        student.Home_Phone__c = '9234565444';
        student.Overall_Grade__c = 'B';
        student.Address__c = 'Rajiv Technology';
        student.City__c = 'Mathura';
        student.Pincode__c = 281203;
        student.State__c = 'Uttar Pradesh';
        student.RecordTypeId = '0125i0000000qmAAAQ'; //Record Type Id = Teacher
        //Class Details   
        student.Section__c = 'C';
        student.Class__c = 'B.Sc';
        student.Stream__c = 'Science';
        //Semester Information
        student.X1st_Sem_Back__c = False;
        student.X1st_Sem_Percentage__c = 56;
        student.X2nd_Sem_Back__c = False;
        student.X2nd_Sem_Percentage__c = 60;
        student.X3rd_Sem_Back__c = False;
        student.X3rd_Sem_Percentage__c = 72;
        student.X4th_Sem_Back__c = True;
        student.X4th_Sem_Percentage__c = 69;
        student.Subjects_in_which_Back_1st_Sem__c = '';
        student.Subjects_in_which_Back_2nd_Sem__c = '';
        student.Subjects_in_which_Back_3rd_Sem__c = '';
        student.Subjects_in_which_Back_4th_Sem__c = 'C++,Data Structure';
        //Fees Details
        student.Current_Year__c = '3rd Year';
        student.Is_Donation__c = False;
        student.Donation_Amount__c = 0;
        student.Fees_Submitted__c = True;
        student.Pending_Fees_Amount__c = 50;
        student.Exam_Fees_Submitted__c = True;
        student.Pending_Exam_Fees__c = 0;
        //Bank Details
        student.Bank_Name__c = 'Central Bank of India';
        student.IFSC_Code__c = 'CBIN0284021';
        student.Account_Number__c = 1463135153;
        student.Bank_Phone_Number__c = '9954199236';
        
        insert student;
    }
    
    public static void displayStudents() {
        List<Student__c> studentsList = [SELECT Student_ID__c, Roll_Number__c, Name, Father_s_Name__c, Class__c, Email__c, Mobile_Number__c, Address__c FROM Student__c ORDER BY CreatedDate];
        for(Student__c student : studentsList) {
            system.debug('Check Student Data : ' + student);
        }
    }
}